// This file is automatically generated. Do not edit it directly.
import { createClient } from '@/utils/supabase/client';
import type { Database } from './types';

// Export as a singleton for compatibility with existing app code
export const supabase = createClient();
